apiVersion: v1
kind: Service
metadata:
  name: crafty-nodeport
  namespace: minecraft-server
spec:
  type: NodePort
  selector:
    app: crafty
  ports:
    - name: web
      port: 8111
      targetPort: 8111
      nodePort: 30443
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 30565