apiVersion: v1
kind: Service
metadata:
  name: crafty-nodeport
  namespace: minecraft-server
spec:
  type: NodePort
  selector:
    app: crafty
  ports:
    - name: web
      port: 8443
      targetPort: 8443
      nodePort: 30111
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 30565