apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 53
          volumeMounts:
          - name: pihole-data
            mountPath: /etc/pihole/db
            subPath: databases
          - name: pihole-data
            mountPath: /etc/pihole
            subPath: config
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data