apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: navidrome
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          ports:
          - containerPort: 4533
          volumeMounts:
            - name: navidrome-data
              mountPath: /data
              subPath: data
            - name: navidrome-data
              mountPath: /music
              subPath: music
            - name: navidrome-data
              mountPath: /backgrounds
              subPath: backgrounds
      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: navidrome-data