apiVersion: v1
kind: Service
metadata:
  name: navidrome-nodeport
  namespace: navidrome
spec:
  type: NodePort
  selector:
    app: navidrome
  ports:
    - name: web
      port: 4533
      targetPort: 4533
      nodePort: 30533